#!/bin/bash

function git-svn-externals-update()
{
	toplevel_directory="$(git rev-parse --show-cdup)"
	[ -n "$toplevel_directory" ] && { echo "please run from the toplevel directory"; return; }

	find .git_externals -type d -name .git | while read gitdir; do
		dir=$(dirname "$gitdir")
	    if [ -d $dir ]; then
		pushd $dir
		echo $dir
		git svn fetch -r HEAD
		git svn rebase
		popd
	    fi
	done
}